- name: LXC-NET | configure /etc/default/lxc-net
  template:
    src: lxc-net.j2
    dest: /etc/default/lxc-net
  register: etc_default

- name: LXC-NET | configure dnsmasq
  template:
    src: dnsmasq.lxc-net.conf.j2
    dest: /etc/lxc/dnsmasq.conf
  register: dnsmasq_conf

- name: LXC-NET | start service
  when: etc_default is changed or dnsmasq_conf is changed
  service:
    name: lxc-net
    state: restarted
